### ISSUE TITLE
bug - Data Sources (splk-dsm) - Permanent entity deletion via the dedicated button through the modification screen performs a temporary deletion instead (but bulk permanent deletion works as expected)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#508] opened 2024-02-23 09:20 UTC
The permanent deletion feature does not work properly in v2.0.83.
The action can be done by the user and the entity disappears. But the KV store remains empty and the entity shows up again after the hybrid tracker finished its next run.

**Comment by guilhemmarchand** [comment] 2024-02-23 17:15
Thanks @sebwurl This sounds like permission issues when the permanent deletion is reqauested through perhaps a non admin user profile (assuming it as you say the KVstore remains empty while the entity itself temporarliy was removed)
Will be investigated ASAP, thank for reporting

**Comment by guilhemmarchand** [comment] 2024-02-23 21:28
Thanks for catching this one, the root cause was identified and it's only happening through the "delete permanent" button via the modification screen. (and for splk-dsm only)
Permanent deletion through bulk edit however works as intended

**Closed** 2024-03-03 22:59 UTC
Labels: bug, high priority, done
