### ISSUE TITLE
bug - Data Source / Data host tracking (splk-dsm/splk-dhm) Persistence of fields issue when the Adaptive tracker runs due to some Python level issues with batch update related code in the specific circumstances of sending a partial update

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#595] opened 2024-04-29 12:59 UTC
In v2.0.89 I'm not able to create a persistent data_max_delay_allowed value.

This analysis of the kvstore trackme_dsm_tenant_<my_tentant> is my starting point:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/e3e410d4-19c0-4554-b593-36443c415906)
- Delay is equal for all analyzed entities
- data_override_lagging_class is set to true for all analyzed entities
- allow_adaptive_delay is set to false for all anlyzed entities

After a while the first entities start to change:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/d289ab0c-2672-4033-8fb8-6524506b5e02)

As more changes are happening, some of the entities do not have a value for allow_adaptive_delay within the kvstore at all (might be handled as "true" as default in the background?)
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/2d6873f3-8f5c-46b3-86db-4741a68f1d1c)

I can verify the changes for data_max_delay_allowed in the audit log for the entity.

data_override_lagging_class & allow_adaptive_delay are included in the macro trackme_dsm_lookup_persistent_fields(1)

**Comment by guilhemmarchand** [comment] 2024-04-29 21:12
Thank you @sebwurl - Great catch as usual.

Long story, short story, we have recently introduced much enhanced Python code to make TrackMe much much fast in all operations, with way better code, systematic usage of batch update and more consistent code.

However, the issue is confirmed and located when the adaptive tracker ran and executed the lagging policy update, such as:

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/write/ds_update_lag_policy" body="{'tenant_id': 'all-idx', 'object_list': 'eventgen-batch:batch_example:daily', 'data_max_delay_allowed': '1801'}"
```

The Python function underneath should have verified that other persistent and non updated fields should not be None before indlucing this into the difference verification.

It's a very tiny difference but has lots of impacts, current:

```
        updated_records = []
        for kvrecord in kvrecords:
            key = kvrecord.get("_key")
            changed = False
            for field, value in update_fields.items():
                if kvrecord.get(field) != value:
                    kvrecord[field] = value
                    changed = True
            if changed:
                kvrecord["mtime"] = time.time()
                updated_records.append(kvrecord)
```

Fixed:

```
        updated_records = []
        for kvrecord in kvrecords:
            key = kvrecord.get("_key")
            changed = False
            for field, value in update_fields.items():
                if value:
                    if kvrecord.get(field) != value:
                        kvrecord[field] = value
                        changed = True
            if changed:
                kvrecord["mtime"] = time.time()
                updated_records.append(kvrecord)
```

The hotfix will be in 2.0.90 which is about to be released in the upcoming hours.

**Comment by guilhemmarchand** [comment] 2024-04-29 23:50
@sebwurl 
TrackMe 2.0.90 was published and addressed this issue, thank you so much for point this one out, this was a difficult one to catch but shouldn't be possible in the future anymore with the code enhancements we have now in TrackMe.

**Closed by guilhemmarchand** 2024-04-29 23:50 UTC
Labels: bug, high priority, done
