### ISSUE TITLE
bug - Virtual Tenant UI - Dropdown text search is not working (affects initial creation and RBAC update modal screens)

### ISSUE THREAD

**Issue by Tinman51** [trackme-limited/trackme-report-issues#304] opened 2023-10-13 14:02 UTC
**Describe the bug**
When attempting to update the Tenant RBAC Ownership account, the drop down filter for selecting the account  does not work. The filter textbox cannot even be selected or receive focus.

**TrackMe version**
2.0.60

**To Reproduce**

1. Open the vTenants page
2. Double click on a tenant tile to open tenant page
3. Click Manage Tenant button
4. Click RBAC & Ownership button
5. Scroll down to "New Ownership" drop down and expand the list 
6. Try to Select or Type into the filter field

**Expected behavior**
Allow the drop down values to be filtered

**Screenshots**
N/A

**Splunk version and deployment:**
Splunk Cloud Classic - 9.0.2305

- Provide the Splunk core version
Search Head Cluster (SHC)

**Additional context**
Ensure you have more than 1 page of users in the list used in the drop down.
form control id="inputUpdateListUser"

**Comment by guilhemmarchand** [comment] 2023-10-13 14:10
Thank you @Tinman51  - confirmed.

It is worth mentionning that you can in Configuration preset the owner, such that this value is pre-populated for you:

https://docs.trackme-solutions.com/admin_guide_rbac.html#

![image](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/5bebe72c-c163-411b-bf11-a95e9fdefa68)

**Comment by guilhemmarchand** [comment] 2023-10-30 11:36
The root cause has been identified, this is due to the tabindex="-1" primitive in HTML.
Will be fixed in 2.0.67

**Closed** 2023-10-30 18:28 UTC
Labels: bug

**Comment by Tinman51** [comment] 2024-01-19 15:37
While the filter function now works, the filter only works on the first returned dataset to the dropdown, so if you have more than the dropdown limit, the filter does not find the appropriate user.
Reproduction steps:
1) Add 200 users to the test system (Note your alphabetical last user name)
2) Open this dropdown per original instructions
3) Try to filter on the name noted as last alphabetical (or a name Not listed in dropdown list but is a user)

Not sure if I should create a new bug or reopen this one, but happy to do whatever.
