### ISSUE TITLE
bug - Workload (splk-wlk) - Timezone issues for system running in non UTC

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#196] opened 2023-07-11 12:18 UTC
Hi,
I'm testing the workload feature in a lab (v2.0.39). Trackers identity saved searches, but some timestamps seem to be wrong.
My sample searches run at least every 15min. But for example the "last time seen" is exactly 2h behind, so according to my local timezone this "last time seen" seems to be the human readable UTC.

**Here is an example:**
My local time is 14:07
According to the Jobs page, my search was successfully created at 14:00.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/da3b2e35-2651-46ea-beab-62e9f4e8622d)

The scheduler log shows a success at 14:00 as well.

In the overview it looks like this (last execution is 2h behind, but last inspection is my current local time).
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/33f359d8-5d82-4e87-805b-41bb5aee021d)

In the details view the last run is at 12:00 as well:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/bea45f0e-5208-40c4-91fc-994ae262bbe2)

I'm also experiencing that a scheduled search search, whose schedule was deleted some hours ago, is not alerted. Maybe this is a side effect of these timestamps.

**Comment by guilhemmarchand** [comment] 2023-07-11 12:46
@sebwurl 
We will have a look, I believe we expect to the system hosting Splunk to be configured in UTC which is why this happens.
This issue was noticed earlier and we shall have the fix shortly.

**Comment by guilhemmarchand** [comment] 2023-07-11 14:18
@sebwurl 
I believe you are testing currently in your lab (because this issue wouldn't happen in Splunk Cloud)

Would you have a chance to test with this beta release which should address the matter?

https://github.com/trackme-limited/trackme-report-issues/releases/tag/beta-version-2.0.43

**Comment by sebwurl** [comment] 2023-07-11 21:35
Yes, the lab is on-prem. I upgraded to the beta-release and with the next tracker run the mentioned timestamps show up correct.

Versioning Metadata is working as well. It did not seem work before, but I was not sure why this could happen. So maybe connected to the timestamp issue as well.

**Comment by guilhemmarchand** [comment] 2023-07-14 13:56
@sebwurl 

This topic is not yet fully addressed in official 2.0.43 which was published today.

The reason is that more testing is required to ensure there won't any regression for most of the users, you were affected because your own lab was running in a non UTC system, however there can be some impacts so we need more verifications prior to publish this change.

However, note that in 2.0.43, when executing a tracker through the UI, the tracker now executes through the system level user rather than the requester, which is also part of the logic in the meaning that prior to 2.0.43 running it via the identify of the requester also means inheriting from the user TZ preferences, while normal execution rely on the owner which is normally using the system level TZ.

As a conclusion, so additional verifications are being processed to fully address this in a the next release train.

**Comment by guilhemmarchand** [comment] 2024-01-05 20:09
@sebwurl 

We believe this issue is now properly addressed in TrackMe 2.0.75.

**Closed by guilhemmarchand** 2024-01-05 20:09 UTC
Labels: bug
