### ISSUE TITLE
bug - Splunk Cloud Classic - DMC deployment issues from Splunk Cloud affect various collecting features from TrackMe due to bad deployment by Splunk Cloud in Classic experience

### ISSUE THREAD

**Issue by Tinman51** [trackme-limited/trackme-report-issues#254] opened 2023-08-17 15:01 UTC
**Describe the bug**
After upgrading from v2.0.39 to 2.0.50, SLA metrics stopped collecting in summary index
index=trackme_summary sourcetype=trackme:state

**TrackMe version**
2.0.50

**To Reproduce**

1. Go to 'search'
2. Search for 'index=trackme_summary sourcetype=trackme:state'
3. 0 records returned

**Expected behavior**
SLA metrics should be collecting for use by SLA UI page

**Screenshots**

**Splunk version and deployment:**

- Provide the Splunk core version
- Search Head Cluster (SHC)

**Additional context**
Checking if any KO's are disabled, but nothing yet that would explain this issue.

**Comment by guilhemmarchand** [comment] 2023-08-18 08:12
@Tinman51 

This sounds suspicious, can you run:

> | tstats count, max(_time) as _time where index=trackme_* earliest=-7d latest=now by index, sourcetype
> | eval duration_since=tostring(round(now()-_time, 0), "duration")

And please share a screenshot of the results from this.

Then:

> | trackme mode=get url=/services/trackme/v2/configuration/request_info

This should render the default indexes:

<img width="1771" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/e2e27ceb-a132-47ed-b814-af91de566d36">

Then check out for errors in:

> index=_internal sourcetype=trackme:custom_commands:trackmecollect log_level=error

Please also run the following SPL and replace "feeds-tracking" with the name of the tenant:

> | trackme mode=post url=/services/trackme/v2/vtenants/tenant_idx_settings body="{'tenant_id': 'feeds-tracking', 'idx_stanza': 'trackme_summary_idx'}"

This should render for instance:

<img width="1775" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/5f1d054f-9ec2-426e-bb63-63ed52552cc4">

If this one generates an error, we can check for:

> index=_internal sourcetype=trackme:rest_api post_tenant_idx_settings

TrackMe uses either the tenant specific settings or the system wide settings, the tenant specific settings can be "global" or a JSON object stored in the KVstore collection:

> | inputlookup trackme_virtual_tenants where tenant_id="feeds-tracking" | eval keyid=_key
> | table tenant_idx_settings, *

<img width="1788" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/d2b86725-acfb-4ee0-8c4c-2f09092ce6b4">

All these functions have various safeties to still render the default indexes when / if an issue occurs, so it should very unlikely the issue comes from this directly, please also:

- Verify that the index is properly defined on the Search Head layer and indexers tiers
- Verify that the Search Head Tier is properly forwarding to the indexers layers

> index=_internal sourcetype=splunkd host=<one of the search heads> | stats count by splunk_server

- Verify that you are looking at the data over a suffiscient time range, Splunk Cloud for instance restricts the time range at the past 30 min by default, if you have a time zone issue and you are looking at the past 30 min you would not see not see the events
- Verify the logs, if there are issues and TrackMe encounters an exception, this will be in the logs as above, you can also open the dashboard "TrackMe - logs inspector" from the menu "Audit & Troubleshoot" and check out for errors.

**Comment by guilhemmarchand** [comment] 2023-08-18 08:17
@Tinman51 

If you are using a service account to run TrackMe searches, it could be that it lacking the right permissions:

https://docs.trackme-solutions.com/admin_guide_configuration.html#service-account-and-permissions

https://docs.trackme-solutions.com/admin_guide_rbac.html

The service accounts need to be able to access to these endpoints which would require at the minimum the capability ``trackmeuseroperations``

Please check this first - sounds like a very good candidate to me.

**Comment by guilhemmarchand** [comment] 2023-08-21 13:47
Hi

Who is the user owner defined on the Vtenant level?

You can double click on the tenant then manage and RBAC and ownership.

I believe your issue is permissions related, the user needs to be a member of trackme_admin to own the required capability.

If it is different from admin then this is required.

If you have access to the owner account, you can run this:

| trackme mode=post url=/services/trackme/v2/vtenants/tenant_idx_settings body="{'tenant_id': 'feeds-tracking', 'idx_stanza': 'trackme_summary_idx'}"

Which would fail if the user does not have the capabilities needed (not your user)

Also, haven't you seen errors in the logs?

**Comment by guilhemmarchand** [comment] 2023-08-26 12:44
@Tinman51 
If you haven't found the root cause, plase drop us an email to:
support@trackme-solutions.com

We will then agree on a time slot to have a look at it together.

**Comment by guilhemmarchand** [comment] 2023-09-03 16:56
@Tinman51 

Would you be running in Splunk Cloud classic by any chance?

We have with another customer this same issue, after some troubleshooting we could identify that for some reasons in their case the parsing of the TrackMe generated events is not happening properly, which we believe is the case because Splunk Cloud does not correctly deploy TrackMe in Splunk Cloud Classic, and does not publish the transforms.conf which parse and override Metadata.

Some more explanations:

TrackMe generates various internal data on the Search Head tier which are parsed by a combination of props and transforms.

As for an example, TrackMe generates data written to a local log file in $SPLUNK_HOME/var/log/

`/opt/splunk/var/log/splunk/trackme_state_events.log`

Splunk indexes automatically log written to $SPLUNK_HOME/var/log, some examples of the log files:

```
2023-09-03 10:09:11,662 INFO trackme_libs.py trackme_gen_state 188 TrackMe State Events, target_index="trackme_summary", target_sourcetype="trackme:state", target_source="current_state_tracking:splk-dsm:feeds-tracking", event={"data_index": "webserver", "data_sourcetype": "apache:access:json", "latest_eventcount_5m": "2", "avg_eventcount_5m": "2", "stdev_eventcount_5m": "0", "perc95_eventcount_5m": "2", "latest_latency_5m": "1", "avg_latency_5m": "1", "stdev_latency_5m": "0", "perc95_latency_5m": "1", "latest_dcount_host_5m": "1", "avg_dcount_host_5m": "1", "stdev_dcount_host_5m": "0", "perc95_dcount_host_5m": "1", "dcount_host": "1.00", "object": "webserver:apache:access:json", "tenant_id": "feeds-tracking", "splk_dsm_is_online": "true", "key": "34d473fd7c3c025ac263cbf6fa5048e2", "priority": "medium", "alias": "webserver:apache:access:json", "data_max_lag_allowed": "3600", "data_max_delay_allowed": "3600", "future_tolerance": "-600", "data_lag_alert_kpis": "all_kpis", "monitored_state": "enabled", "data_monitoring_wdays": "auto:all_days", "data_monitoring_hours_ranges": "auto:all_ranges", "data_override_lagging_class": "false", "min_dcount_host": "any", "latest_flip_time": "1690280647", "latest_flip_state": "green", "object_previous_state": "green", "data_first_time_seen": "1690266331", "outliers_readiness": "True", "data_last_ingest": "1693735541", "data_last_time_seen": "1693735540", "data_last_lag_seen": "205", "data_last_ingestion_lag_seen": "1", "data_eventcount": "232", "data_last_time_seen_idx": "1693739237", "data_last_lag_seen_idx": "-3492", "object_category": "splk-dsm", "data_sample_feature": "enabled", "data_sample_status_colour": "green", "data_sample_mtime": "1693735320", "isAnomaly": "0", "data_sample_lastrun": "1693735320", "isOutlier": "0", "tenant_pref_outliers_set_state": "1", "tenant_pref_data_sampling_set_state": "1", "manual_wdays_regex": "^(auto:all_days)$", "isUnderMonitoringDays": "true", "current_hour_range": "10", "isUnderMonitoringHours": "true", "data_last_time_seen (translated)": "03 Sep 2023 10:05", "data_last_time_seen_idx (translated)": "03 Sep 2023 11:07", "data_last_ingest (translated)": "03 Sep 2023 10:05", "object_group_state": "red", "status_message": "Good: entity status is green, latest data available is 03 Sep 2023 10:05 (205 seconds from now), and monitoring conditions are met.", "anomaly_reason": "none", "search_mode": "tstats", "current_state": "green", "previous_state": "green", "_time": "1693735745"}
2023-09-03 10:09:11,662 INFO trackme_libs.py trackme_gen_state 188 TrackMe State Events, target_index="trackme_summary", target_sourcetype="trackme:state", target_source="current_state_tracking:splk-dsm:feeds-tracking", event={"data_index": "webserver", "data_sourcetype": "apache:error", "object": "webserver:apache:error", "tenant_id": "feeds-tracking", "splk_dsm_is_online": "true", "key": "0c6dc908897939e9ba342eb6999218c6", "priority": "medium", "alias": "webserver:apache:error", "data_max_lag_allowed": "3600", "data_max_delay_allowed": "3600", "future_tolerance": "-600", "data_lag_alert_kpis": "all_kpis", "monitored_state": "enabled", "data_monitoring_wdays": "auto:all_days", "data_monitoring_hours_ranges": "auto:all_ranges", "data_override_lagging_class": "false", "min_dcount_host": "any", "latest_flip_time": "1693735148", "latest_flip_state": "red", "object_previous_state": "red", "data_first_time_seen": "1690270845", "outliers_readiness": "True", "data_last_ingest": "1693727728", "data_last_time_seen": "1693731325", "data_last_lag_seen": "4420", "data_last_ingestion_lag_seen": "-3597", "data_eventcount": "3", "data_last_time_seen_idx": "1693739237", "data_last_lag_seen_idx": "-3492", "object_category": "splk-dsm", "data_sample_feature": "disabled", "data_sample_status_colour": "orange", "data_sample_mtime": "1690281720", "isAnomaly": "0", "data_sample_lastrun": "1690281720", "isOutlier": "0", "tenant_pref_outliers_set_state": "1", "tenant_pref_data_sampling_set_state": "1", "manual_wdays_regex": "^(auto:all_days)$", "isUnderMonitoringDays": "true", "current_hour_range": "10", "isUnderMonitoringHours": "true", "data_last_time_seen (translated)": "03 Sep 2023 08:55", "data_last_time_seen_idx (translated)": "03 Sep 2023 11:07", "data_last_ingest (translated)": "03 Sep 2023 07:55", "object_group_state": "red", "status_message": "Alert: entity status is red, monitoring conditions are not met due to lagging or interruption in the data flow, latest data available is 03 Sep 2023 08:55 (4420 seconds from now) and ingestion latency is approximately -3597 seconds, max lag configured is 3600 seconds.", "anomaly_reason": "delay_threshold_breached", "search_mode": "tstats", "current_state": "red", "previous_state": "red", "_time": "1693735745"}
```

TrackMe parses these log files using a props.conf stanza based on the source:

props.conf

```
#
# TrackMe events
#

[source::...trackme_state_events.log]
KV_MODE = auto
sourcetype = trackme:state
SHOULD_LINEMERGE=false
LINE_BREAKER=([\r\n]+)\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}
CHARSET=UTF-8
TIME_PREFIX=^
TIME_FORMAT=%Y-%m-%d %H:%M:%S,%3N
TRUNCATE=0

TRANSFORMS-eventslog = trackme_events_001_index_redirect,trackme_events_002_sourcetype_redirect,trackme_events_003_source_redirect,trackme_events_004_raw
```

As per the configuration above, TrackMe applies a list of transforms to override Splunk Metadata such as the index target:

transforms.conf

```
#
# events
#

[trackme_events_001_index_redirect]
DEST_KEY = _MetaData:Index
FORMAT = $1
REGEX = target_index=\"([^\"]+)\"

[trackme_events_002_sourcetype_redirect]
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::$1
REGEX = target_sourcetype=\"([^\"]+)\"

[trackme_events_003_source_redirect]
DEST_KEY = MetaData:Source
FORMAT = source::$1
REGEX = target_source=\"([^\"]+)\"

[trackme_events_004_raw]
LOOKAHEAD = 20000
DEST_KEY = _raw
FORMAT = $1
REGEX = event=(.*)

```
Via these builtin configuration, the events should be redirected to the proper index extracted by the regular expressions defined in the transforms:

`target_index="trackme_summary"`

We can observe that currently these events are instead indexed in the _internal Splunk index, meaning these transforms are not been applied as expected.

It was confirmed by the editor of TrackMe that this situation does not occur on Splunk Cloud Victoria experience, nor on Splunk Enterprise.

The parsing of these events is to performed by Splunk on the Search Head Tier, Search Heads are full instance of Splunk and parse events before forwarding events to the indexing tier in Splunk Cloud, we believe the most likely explanation is an incomplete deployment of the application and in particular the associated transforms.conf which should be deployed properly to the Search Head cluster members, and not only the indexers. (Improper partitioning made by Splunk Cloud automation?)

**Comment by Tinman51** [comment] 2023-09-05 13:22
We are on Classic cloud.

 

Are there steps published anywhere that I can create a ticket for Splunk to correct the issue?

**Comment by guilhemmarchand** [comment] 2023-09-05 13:41
@Tinman51 

That's very interestiing, and therefore makes full of sense.

What I strongly suspect is that for some reasons in Splunk Cloud Classic, the "source" stanza for the parsing of the events in the transforms are not published to the Search Head tier as it should, or any of these props/transforms which are part of the application.

However I do not have the proof of that yet, it could something else too, but we know this issue does not happen in Splunk Enterprise & Splunk Cloud Victoria, therefore the logical candidate is deployment related.

You can take these exact steps and explanations I have shared in this thread to open a case to Splunk:

We have shared the same to our customer and they're support to open a case too:

****


- Subject: Parsing of TrackMe internal data is not performed properly in our Splunk Cloud Search Tier

- Content:

We have identified that an issue occurs in our deployment of the application TrackMe (https://splunkbase.splunk.com/app/4621), we believe this issue is caused by an incomplete deployment of the application performed by Splunk.

TrackMe generates various internal data on the Search Head tier which are parsed by a combination of props and transforms.

As for an example, TrackMe generates data written to a local log file in $SPLUNK_HOME/var/log/

/opt/splunk/var/log/splunk/trackme_state_events.log

Splunk indexes automatically log written to $SPLUNK_HOME/var/log, some examples of the log files:

2023-09-03 10:09:11,662 INFO trackme_libs.py trackme_gen_state 188 TrackMe State Events, target_index="trackme_summary", target_sourcetype="trackme:state", target_source="current_state_tracking:splk-dsm:feeds-tracking", event={"data_index": "webserver", "data_sourcetype": "apache:access:json", "latest_eventcount_5m": "2", "avg_eventcount_5m": "2", "stdev_eventcount_5m": "0", "perc95_eventcount_5m": "2", "latest_latency_5m": "1", "avg_latency_5m": "1", "stdev_latency_5m": "0", "perc95_latency_5m": "1", "latest_dcount_host_5m": "1", "avg_dcount_host_5m": "1", "stdev_dcount_host_5m": "0", "perc95_dcount_host_5m": "1", "dcount_host": "1.00", "object": "webserver:apache:access:json", "tenant_id": "feeds-tracking", "splk_dsm_is_online": "true", "key": "34d473fd7c3c025ac263cbf6fa5048e2", "priority": "medium", "alias": "webserver:apache:access:json", "data_max_lag_allowed": "3600", "data_max_delay_allowed": "3600", "future_tolerance": "-600", "data_lag_alert_kpis": "all_kpis", "monitored_state": "enabled", "data_monitoring_wdays": "auto:all_days", "data_monitoring_hours_ranges": "auto:all_ranges", "data_override_lagging_class": "false", "min_dcount_host": "any", "latest_flip_time": "1690280647", "latest_flip_state": "green", "object_previous_state": "green", "data_first_time_seen": "1690266331", "outliers_readiness": "True", "data_last_ingest": "1693735541", "data_last_time_seen": "1693735540", "data_last_lag_seen": "205", "data_last_ingestion_lag_seen": "1", "data_eventcount": "232", "data_last_time_seen_idx": "1693739237", "data_last_lag_seen_idx": "-3492", "object_category": "splk-dsm", "data_sample_feature": "enabled", "data_sample_status_colour": "green", "data_sample_mtime": "1693735320", "isAnomaly": "0", "data_sample_lastrun": "1693735320", "isOutlier": "0", "tenant_pref_outliers_set_state": "1", "tenant_pref_data_sampling_set_state": "1", "manual_wdays_regex": "^(auto:all_days)$", "isUnderMonitoringDays": "true", "current_hour_range": "10", "isUnderMonitoringHours": "true", "data_last_time_seen (translated)": "03 Sep 2023 10:05", "data_last_time_seen_idx (translated)": "03 Sep 2023 11:07", "data_last_ingest (translated)": "03 Sep 2023 10:05", "object_group_state": "red", "status_message": "Good: entity status is green, latest data available is 03 Sep 2023 10:05 (205 seconds from now), and monitoring conditions are met.", "anomaly_reason": "none", "search_mode": "tstats", "current_state": "green", "previous_state": "green", "_time": "1693735745"}
2023-09-03 10:09:11,662 INFO trackme_libs.py trackme_gen_state 188 TrackMe State Events, target_index="trackme_summary", target_sourcetype="trackme:state", target_source="current_state_tracking:splk-dsm:feeds-tracking", event={"data_index": "webserver", "data_sourcetype": "apache:error", "object": "webserver:apache:error", "tenant_id": "feeds-tracking", "splk_dsm_is_online": "true", "key": "0c6dc908897939e9ba342eb6999218c6", "priority": "medium", "alias": "webserver:apache:error", "data_max_lag_allowed": "3600", "data_max_delay_allowed": "3600", "future_tolerance": "-600", "data_lag_alert_kpis": "all_kpis", "monitored_state": "enabled", "data_monitoring_wdays": "auto:all_days", "data_monitoring_hours_ranges": "auto:all_ranges", "data_override_lagging_class": "false", "min_dcount_host": "any", "latest_flip_time": "1693735148", "latest_flip_state": "red", "object_previous_state": "red", "data_first_time_seen": "1690270845", "outliers_readiness": "True", "data_last_ingest": "1693727728", "data_last_time_seen": "1693731325", "data_last_lag_seen": "4420", "data_last_ingestion_lag_seen": "-3597", "data_eventcount": "3", "data_last_time_seen_idx": "1693739237", "data_last_lag_seen_idx": "-3492", "object_category": "splk-dsm", "data_sample_feature": "disabled", "data_sample_status_colour": "orange", "data_sample_mtime": "1690281720", "isAnomaly": "0", "data_sample_lastrun": "1690281720", "isOutlier": "0", "tenant_pref_outliers_set_state": "1", "tenant_pref_data_sampling_set_state": "1", "manual_wdays_regex": "^(auto:all_days)$", "isUnderMonitoringDays": "true", "current_hour_range": "10", "isUnderMonitoringHours": "true", "data_last_time_seen (translated)": "03 Sep 2023 08:55", "data_last_time_seen_idx (translated)": "03 Sep 2023 11:07", "data_last_ingest (translated)": "03 Sep 2023 07:55", "object_group_state": "red", "status_message": "Alert: entity status is red, monitoring conditions are not met due to lagging or interruption in the data flow, latest data available is 03 Sep 2023 08:55 (4420 seconds from now) and ingestion latency is approximately -3597 seconds, max lag configured is 3600 seconds.", "anomaly_reason": "delay_threshold_breached", "search_mode": "tstats", "current_state": "red", "previous_state": "red", "_time": "1693735745"}

TrackMe parses these log files using a props.conf stanza based on the source:

props.conf

#
# TrackMe events
#

[source::...trackme_state_events.log]
KV_MODE = auto
sourcetype = trackme:state
SHOULD_LINEMERGE=false
LINE_BREAKER=([\r\n]+)\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}
CHARSET=UTF-8
TIME_PREFIX=^
TIME_FORMAT=%Y-%m-%d %H:%M:%S,%3N
TRUNCATE=0

TRANSFORMS-eventslog = trackme_events_001_index_redirect,trackme_events_002_sourcetype_redirect,trackme_events_003_source_redirect,trackme_events_004_raw



As per the configuration above, TrackMe applies a list of transforms to override Splunk Metadata such as the index target:

transforms.conf

#
# events
#

[trackme_events_001_index_redirect]
DEST_KEY = _MetaData:Index
FORMAT = $1
REGEX = target_index=\"([^\"]+)\"

[trackme_events_002_sourcetype_redirect]
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::$1
REGEX = target_sourcetype=\"([^\"]+)\"

[trackme_events_003_source_redirect]
DEST_KEY = MetaData:Source
FORMAT = source::$1
REGEX = target_source=\"([^\"]+)\"

[trackme_events_004_raw]
LOOKAHEAD = 20000
DEST_KEY = _raw
FORMAT = $1
REGEX = event=(.*)


Via these builtin configuration, the events should be redirected to the proper index extracted by the regular expressions defined in the transforms:

target_index="trackme_summary"

We can observe that currently these events are instead indexed in the _internal Splunk index, meaning these transforms are not been applied as expected.

It was confirmed by the editor of TrackMe that this situation does not occur on Splunk Cloud Victoria experience, nor on Splunk Enterprise.

The parsing of these events is to performed by Splunk on the Search Head Tier, Search Heads are full instance of Splunk and parse events before forwarding events to the indexing tier in Splunk Cloud, we believe the most likely explanation is an incomplete deployment of the application and in particular the associated transforms.conf which should be deployed properly to the Search Head cluster members, and not only the indexers. (Improper partitioning made by Splunk Cloud automation?)

Attached the transforms.conf from TrackMe.

**Comment by guilhemmarchand** [comment] 2023-09-05 14:20
@Tinman51 
If you get to have a case opened, and if you are happy with that, can drop us an email with the case number please:
support@trackme-solutions.com
Then we can try to have chat with our contacts to help solving this issue.

**Comment by guilhemmarchand** [comment] 2023-09-06 16:23
@Tinman51 
Did you have a chance to open a support case?
We are trying to push up for the resolution of this issue

**Comment by guilhemmarchand** [comment] 2023-09-07 10:02
@Tinman51 

This issue is being progressed with Splunk, after a trooubleshooting session, we could identify that the root cause was indeed a deployment issue on the Splunk Cloud side, which is performed by a component called "DMC" in Splunk Cloud Classic.

What is happening is that on the Search Head tier, the DMC does not deploy the entire transforms configuration, and the "DEST_KEY" is systematically missing.

As for an example:

```
[trackme_events_001_index_redirect]
DEST_KEY = _MetaData:Index
FORMAT = $1
REGEX = target_index=\"([^\"]+)\"
```

Ends up deployed as:

```
[trackme_events_001_index_redirect]
FORMAT = $1
REGEX = target_index=\"([^\"]+)\"
```

On the Search Heads tier, but is properly deployed on the indexers.
However, in this context indexers do not matter as the parsing lives on the Search Heads and not the indexers.

As a conclusion, if you wish to open the support case, you can well refer to this.

**Comment by guilhemmarchand** [comment] 2023-09-11 07:29
@Tinman51 

We have released a new version, release 2.0.56, which addresses the DMC Splunk Cloud bugs by relying on ingest evals instead of Metadata override based on regex transforms.
While these issues are purely Splunk Cloud issues, and what TrackMe was doing was perfectly best Splunk standards, we have decided that it would be worth the jump as we could also enhance things in the same time, and in anyway it would have taken ages for Splunk to fix their issues, if eventually it was fixed.

Once the release is vetted, please upgrade and confirm your feeedback.

If we have no news from you, we will close this issue accordingly.

Thanks for participating in this bug identification.

**Comment by Tinman51** [comment] 2023-09-11 14:22
We will update once it is vetted, thanks for the follow up and you can close out the bug.

 

Thanks!

**Comment by guilhemmarchand** [comment] 2023-09-20 08:47
Hi @Tinman51 

Did you have the chance to get the latest release deployed in your Cloud stack, and if so can you please confirm if the issues are fixed accordingly?

Your answer will be very previous to us.

Thank you in advance

TrackMe

**Comment by Tinman51** [comment] 2023-09-26 23:27
We just got 2.0.58 installed on our Classic Cloud Stack, I don’t think they cycled the SHC, so seems like the trackme:state and others are NOT collecting at all now (not the trackme OR _internal indexes).

 

I have reached out again to Splunk support to see what is happening with the installation.

**Comment by guilhemmarchand** [comment] 2023-09-26 23:34
@Tinman51 

We have identified that the release 2.0.58 did not fix the issue because the INDEXED_EXTRACTION was not deployed to the Search Heads either due to SLIM partitionning. (and it is required for the change to INGEST_EVAL)

Therefore, we have released 2.0.60 for that purpose:
https://docs.trackme-solutions.com/releasenotes.html#version-2-0-60-build-1695681952-25-09-2023

It contains spec files for props and transforms which instruct SLIM to publish the stanzas and their parameters to the Search Heads effectively - which will address the issue.

The release is currently pending from vetting.

**Comment by Tinman51** [comment] 2023-10-11 00:03
We have finally gotten 2.0.60 installed on our stack, but still looks like the events still aren’t being stored in the summary index.

 

Now they have just updated our stack, so will see if there is any improvement in a few hours.

**Comment by guilhemmarchand** [comment] 2023-10-11 00:44
@Tinman51 

Can you do me a favour please, share the name of your stack by email:
support@trackme-solutions.com
Thank you

**Comment by guilhemmarchand** [comment] 2023-10-12 12:57
@Tinman51 

We have finally been able to fully understand and address issues with Splunk Cloud Classic.
The release 2.0.61 will be published shortly, a compatible mode will be available allow you to switch to a different mechanism and finally address your issues.

We will get it in touch by the EOW

**Comment by Tinman51** [comment] 2023-10-13 13:37
Thanks

**Comment by guilhemmarchand** [comment] 2023-10-13 13:39
Release 2.0.61 was published yesterday - it does address effectively the SLIM partition issues, and we have put several measures to be able to detect these types of issues in the future.

**Comment by guilhemmarchand** [comment] 2023-10-17 17:21
Please re-open this issue if you have any issue after upgrading >= 2.0.61

**Closed by guilhemmarchand** 2023-10-17 17:21 UTC
Labels: question
