### ISSUE TITLE
TrackMe bug report - High priority host disappeared from Event Endpoints Tracking

### ISSUE THREAD

**Issue by bdcrandall** [trackme-limited/trackme-report-issues#586] opened 2024-04-26 19:46 UTC
**Describe the bug**
Host only shows in Event Endpoints Tracking when "Show disabled entities" is True.  But as far as I can tell the entity is not disabled.

**TrackMe version**
2.0.87

**To Reproduce**
I'm not certain but here's what I know:
1. The priority of the host was set to high
2. It triggered an alert due to latency
3. The alert was auto-acknowledged
4. The host went back to green status correctly when more data was received
5. The host appears to be a disabled entity but the Monitoring state is enabled and we have no disabled host entities.

**Expected behavior**
The host should appear when "Show disabled entities" is False.

**Screenshots**
Hostnames and users are redacted.  All hostnames are the same.

Host appears when "Show disabled entities:" is True.  Monitoring state is enabled:
![trackme_endpoints_bug04](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/df6b9c14-f19c-4fb7-a5dc-e83db466b3e5)

Host no longer appears when "Show disabled entities" is False:
![trackme_endpoints_bug03](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/06b3f961-7409-4fba-92fd-7ee632f175d5)

Status flip / acks:
![trackme_endpoints_bug01](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/c416d9ba-6933-4d1c-9e6c-83c64b3bf362)

JSON of event acks:
![trackme_endpoints_bug02](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/4b4a67c5-b33c-46bc-b724-ee47b6ef6600)

**Splunk version and deployment:**
Splunk Cloud
Version: 9.0.2303.201
Build: 5480631d4591
Experience: Classic
Standalone search head

**Additional context**

**Comment by guilhemmarchand** [comment] 2024-04-29 23:58
Hi @bdcrandall 

Sorry for late coming back to you.

I beliebe this issue in not possible in the last versions, the last vetted currently is 2.0.88, we are expecting 2.0.89 to be vetted shortly too. (and we already have 2.0.90 waiting now...)

Could you check what the entity is looking like with the search:

```
| trackmegetcoll tenant_id=mytenant component=dsm
```

--> Update mytenant and the component
--> This command represents the exact same view than from the UI, underneath thes goes through the same real time decision maker concepts in TrackMe

**Comment by bdcrandall** [comment] 2024-04-30 12:34
I updated to v2.0.88 and the entity still only appears when I set "Show disabled entities" to True.  I ran the `trackmegetcoll` command and it returns a ton of JSON.  Which fields should I examine?

**Comment by guilhemmarchand** [comment] 2024-04-30 21:46
@bdcrandall 

My point was to say that this command is underneath the exact 100% UI view reflect because both call the same API endpoints underneath.

So if you do:

| trackmegetcoll tenant_id=mytenant component=dsm
| search object="myobject"

Then we can see the value of the fields as interpretered by the UI.

However - let us triple check if we missed anything, I understand the host appears only when show disabled is true while the host is meant to monitored_state = enabled (so the comment was to check this value of the field)

**Comment by guilhemmarchand** [comment] 2024-04-30 22:19
@bdcrandall 
What would be useful would be you could send to support@trackme-solutions.com the resulting JSON from one of these particular hosts which disappeared in that context? You could anonymize the very few fields as needed (object / alias)

Then we could better understand what the potential root cause could be

**Comment by bdcrandall** [comment] 2024-05-01 21:16
One peculiar thing I noticed is that when I run the `| trackmegetcoll` command, I get two results for that object.  In fact, 6,622 objects return 2 results from the command, while 6,193 objects return only 1.  It may be coincidence but of the few I spot checked, all the ones with 1 result appear correctly in the table and all the ones with 2 results need "Show disabled entities" set to True to appear.

I also noticed that the table pagination does not work correctly when "Show disabled entities" is set to True in the dashboard.  I'll have <20 results spread across 3 pages!

Hopefully this info helps.  If not, I'll see if I can get some redacted JSON uploaded tomorrow.

**Comment by guilhemmarchand** [comment] 2024-05-16 21:56
@bdcrandall 
My apologises for coming back to you lately on this one.
The root cause was identified and fixed in the very last release 2.0.92, we are still waiting for it to be vetted.

What happened actually was deep in the code, when we retrieve Kvstore records natively in Python, we process with various level of optimization to be able to highly scale through the many complex pipelines of decision. (the decision maker)

With splk-dhm, it turns out that we have records much biggers that with other components, the current optimization was attenpting to retrieve a too large number of records per iteration, leading to incomplete retrieval of the records.

This issue is now fully addressed - thank you for patience on this issue.

**Comment by guilhemmarchand** [comment] 2024-06-12 17:06
Hi @bdcrandall 
This should have been properly addressed as mentioned - please let me know if we can close this one too ;-)

**Comment by guilhemmarchand** [comment] 2024-06-21 08:24
Closed for inactivity, pleae re-open if needed - thank you

**Closed by guilhemmarchand** 2024-06-21 08:24 UTC
Labels: bug, already fixed
